apiVersion: v1
kind: ConfigMap
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: <registry_name>
      prefix: <registry_url_without_http>
      api_url: <registry_url>
      credentials: pullsecret: <registry_secret_name>
      default: true
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-ssh-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-ssh-config